openapi: 3.0.1
info:
  title: API de Compras - Petshops
  description: Endpoints para registrar y listar compras en tiendas PETSHOP
  version: 1.0.0
servers:
- url: https://2racbwta6d.execute-api.us-east-1.amazonaws.com/prod
paths:
  /compras/registrar:
    post:
      tags:
      - Compras
      summary: Registrar una compra
      description: "Registra una compra de un producto, disminuye el stock y guarda los detalles."
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        example: Bearer tu_token_uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/compras_registrar_body"
        required: true
      responses:
        "200":
          description: Compra registrada exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200"
        "400":
          description: Error del cliente (faltan datos o stock insuficiente)
        "403":
          description: Token inválido o expirado
        "500":
          description: Error interno del servidor
  /compras/listar:
    get:
      tags:
      - Compras
      summary: Listar compras del usuario
      description: Devuelve todas las compras hechas por el usuario autenticado por token.
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        example: Bearer tu_token_uuid
      responses:
        "200":
          description: Lista de compras obtenida exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inline_response_200_1"
        "403":
          description: Token inválido o expirado
        "500":
          description: Error interno del servidor
components:
  schemas:
    compras_registrar_body:
      required:
      - producto_id
      - tenant_id
      type: object
      properties:
        producto_id:
          type: string
          example: PROD001
        tenant_id:
          type: string
          example: PETSHOP1
    inline_response_200:
      type: object
      properties:
        mensaje:
          type: string
        compra_id:
          type: string
    inline_response_200_1:
      type: object
      properties:
        compras:
          type: array
          items:
            type: object
