openapi: 3.0.0
info:
  title: API de Compras - Petshops
  description: Endpoints para registrar y listar compras en tiendas PETSHOP
  version: 1.0.0
servers:
  - url: https://2racbwta6d.execute-api.us-east-1.amazonaws.com/prod

paths:
  /compras/registrar:
    post:
      tags:
        - Compras
      summary: Registrar una compra
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompraRegistro'
      responses:
        '200':
          description: Compra registrada exitosamente
        '400':
          description: Faltan datos o stock insuficiente
        '403':
          description: Token inválido o expirado
        '500':
          description: Error interno del servidor

  /compras/listar:
    get:
      tags:
        - Compras
      summary: Listar compras del usuario autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de compras
        '403':
          description: Token inválido o expirado
        '500':
          description: Error interno del servidor

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: UUID
  schemas:
    CompraRegistro:
      type: object
      required:
        - producto_id
        - tenant_id
      properties:
        producto_id:
          type: string
          example: prod201
        tenant_id:
          type: string
          example: PETSHOP3
