openapi: 3.0.0
info:
  title: API de Productos
  version: 1.0.0
  description: Documentación de la API para gestión de productos
servers:
  - url: https://tu-api-productos.execute-api.us-east-1.amazonaws.com/prod

paths:
  /producto/crear:
    post:
      summary: Crear un producto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductoEntrada'
      responses:
        '200':
          description: Producto creado exitosamente

  /producto/buscar:
    post:
      summary: Buscar un producto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - tenant_id
                - producto_id
              properties:
                tenant_id:
                  type: string
                producto_id:
                  type: string
      responses:
        '200':
          description: Detalle del producto

  /producto/eliminar:
    delete:
      summary: Eliminar un producto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - tenant_id
                - producto_id
              properties:
                tenant_id:
                  type: string
                producto_id:
                  type: string
      responses:
        '200':
          description: Producto eliminado exitosamente

  /producto/listar:
    post:
      summary: Listar productos con paginación
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                tenant_id:
                  type: string
                startKey:
                  type: string
      responses:
        '200':
          description: Lista de productos

  /producto/modificar:
    put:
      summary: Modificar un producto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - tenant_id
                - producto_id
              properties:
                tenant_id:
                  type: string
                producto_id:
                  type: string
                nombre:
                  type: string
                precio:
                  type: number
      responses:
        '200':
          description: Producto modificado exitosamente

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: UUID
  schemas:
    ProductoEntrada:
      type: object
      required:
        - tenant_id
        - producto_id
        - nombre
        - precio
      properties:
        tenant_id:
          type: string
        producto_id:
          type: string
        nombre:
          type: string
        precio:
          type: number
